export const offers = [
    {
        year: '2019',
        make: 'Volkswagen',
        model: 'Tiguan',
        fuel: 'Diesel',
        transmission: 'Automatic',
        mileage: 19855,
        price: 34888,
        img: 'tiguan',
        id: 1,
        isNew: false,
        sold: false,
    },
    {
        year: '2014',
        make: 'Toyota',
        model: 'Highlander XLE',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 69000,
        price: 27875,
        img: 'highlanderxle',
        id: 2,
        isNew: true,
        sold: false,
    },
    {
        year: '2017',
        make: 'Lexus',
        model: 'RX 350 LUXURY',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 39850,
        price: 38775,
        img: 'rx350lux',
        id: 3,
        isNew: false,
        sold: false,
    },
    {
        year: '2016',
        make: 'Toyota',
        model: 'Highlander LE AWD',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 104000,
        price: 23728,
        img: 'highlanderle',
        id: 4,
        isNew: false,
        sold: false,
    },
    {
        year: '2017',
        make: 'Hyundai',
        model: 'Elantra',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 95000,
        price: 11778,
        img: 'elantra',
        id: 5,
        isNew: false,
        sold: false,
    },
    {
        year: '2016',
        make: 'Mercedes-Benz',
        model: 'GLE-Class',
        fuel: 'Diesel',
        transmission: 'Automatic',
        mileage: 59800,
        price: 38878,
        img: 'gle',
        id: 6,
        isNew: false,
        sold: false,
    },
    {
        year: '2015',
        make: 'Toyota',
        model: 'Venza AWD XLE',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 99000,
        price: 18620,
        img: 'venza',
        id: 7,
        isNew: false,
        sold: true,
    },
    {
        year: '2016',
        make: 'Lexus',
        model: 'RX 350 F-SPORT',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 86000,
        price: 34888,
        img: 'rx350fsport',
        id: 8,
        isNew: true,
        sold: false,
    },
    {
        year: '2019',
        make: 'Volkswagen',
        model: 'Tiguan',
        fuel: 'Diesel',
        transmission: 'Automatic',
        mileage: 19855,
        price: 34888,
        img: 'tiguan',
        id: 9,
        isNew: false,
        sold: false,
    },
    {
        year: '2014',
        make: 'Toyota',
        model: 'Highlander XLE',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 69000,
        price: 27875,
        img: 'highlanderxle',
        id: 10,
        isNew: false,
        sold: false,
    },
    {
        year: '2017',
        make: 'Lexus',
        model: 'RX 350 LUXURY',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 39850,
        price: 38775,
        img: 'rx350lux',
        id: 11,
        isNew: false,
        sold: false,
    },
    {
        year: '2016',
        make: 'Toyota',
        model: 'Highlander LE AWD',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 104000,
        price: 23728,
        img: 'highlanderle',
        id: 12,
        isNew: false,
        sold: false,
    },
    {
        year: '2019',
        make: 'Volkswagen',
        model: 'Tiguan',
        fuel: 'Diesel',
        transmission: 'Automatic',
        mileage: 19855,
        price: 34888,
        img: 'tiguan',
        id: 13,
        isNew: true,
        sold: false,
    },
    {
        year: '2014',
        make: 'Toyota',
        model: 'Highlander XLE',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 69000,
        price: 27875,
        img: 'highlanderxle',
        id: 14,
        isNew: false,
        sold: false,
    },
    {
        year: '2017',
        make: 'Lexus',
        model: 'RX 350 LUXURY',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 39850,
        price: 38775,
        img: 'rx350lux',
        id: 15,
        isNew: false,
        sold: false,
    },
    {
        year: '2016',
        make: 'Toyota',
        model: 'Highlander LE AWD',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 104000,
        price: 23728,
        img: 'highlanderle',
        id: 16,
        isNew: false,
        sold: false,
    },
    {
        year: '2017',
        make: 'Hyundai',
        model: 'Elantra',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 95000,
        price: 11778,
        img: 'elantra',
        id: 17,
        isNew: false,
        sold: false,
    },
    {
        year: '2016',
        make: 'Mercedes-Benz',
        model: 'GLE-Class',
        fuel: 'Diesel',
        transmission: 'Automatic',
        mileage: 59800,
        price: 38878,
        img: 'gle',
        id: 18,
        isNew: false,
        sold: false,
    },
    {
        year: '2015',
        make: 'Toyota',
        model: 'Venza AWD XLE',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 99000,
        price: 18620,
        img: 'venza',
        id: 19,
        isNew: false,
        sold: false,
    },
    {
        year: '2016',
        make: 'Lexus',
        model: 'RX 350 F-SPORT',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 86000,
        price: 34888,
        img: 'rx350fsport',
        id: 20,
        isNew: true,
        sold: false,
    },
    {
        year: '2019',
        make: 'Volkswagen',
        model: 'Tiguan',
        fuel: 'Diesel',
        transmission: 'Automatic',
        mileage: 19855,
        price: 34888,
        img: 'tiguan',
        id: 21,
        isNew: false,
        sold: false,
    },
    {
        year: '2014',
        make: 'Toyota',
        model: 'Highlander XLE',
        fuel: 'Gas',
        transmission: 'Automatic',
        mileage: 69000,
        price: 27875,
        img: 'highlanderxle',
        id: 22,
        isNew: false,
        sold: false,
    },
]